name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  DOCKER_REPOSITORY_NAME: speechemotionrecognition
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
    - name: docker build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/$DOCKER_REPOSITORY_NAME:$(date +%s)
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/$DOCKER_REPOSITORY_NAME
